### ISSUE TITLE
Join forces

### ISSUE THREAD

**Issue by ghost** [wasinger/htmlpagedom#13]
Can you join forces with this guy and implement some more? https://code.google.com/archive/p/phpquery/

(BEWARE: your insert functions already work better for some reason.)

I added:
`
    public function __get($name) {
        switch($name) {
            case 'count':
            case 'length':
                return count($this);
        }
        throw new \Exception('Not implemented!');
    }

`
to start.  I like where this is headed.  I dream of a world where your server, template, model can be written in 1 language; jQuery!

**Comment by wasinger** [comment]
Thanks for your interest in this project. If you want more functions please feel free to submit pull requests. 
Adding a `length()` method might be a good idea but I don't really like your implementation via the magic `__get()` method. I prefer real functions for better IDE autocompletion support instead of magical ones.

**Comment by bjcullinan** [comment]
Hmm just trying to be consistent with the library, jquery's length method
is also not a method but instead a field in the object. Phpstorm recognizes
magic methods and switch cases just fine. I guess you could set length
every time the items list changes but that seems like more work.

**Comment by wasinger** [comment]
proposed _get() function for getting $crawler->length implemented in v1.3.0
