### ISSUE TITLE
Is this project still maintaining?

### ISSUE THREAD

**Issue by shtse8** [wasinger/htmlpagedom#17]
I have tried DiDom, HtmlDomParser and many others, but unluckily no one is good enough.
So I want to use this library on my project, but I am worrying is this project still active and the last commit was half year ago.

**Comment by wasinger** [comment]
This project is still maintained. There was no development activity in the last months just because it already does what it should do (i.e. it has all the features I need in my projects).
If you find bugs or want to suggest a new feature please open a ticket or fork the project and submit pull requests.

**Comment by shtse8** [comment]
Perfect. But why don't change the `filter` to `find`  (same as `JQuery`)?
