### ISSUE TITLE
Allow symfony 6

### ISSUE THREAD

**Issue by yellow1912** [wasinger/htmlpagedom#39]
Can we allow symfony 6? I think there is no BC in this.

**Comment by wasinger** [comment]
The problem is: Unit testing on Travis CI seems to be broken, at least a pull request for compatibility with PHP 8 (#37) is not passing tests. Without green tests I can't merge PRs. Sadly, I had no time at all to investigate in this problem.
My own projects where I use this lib are still on Symfony 4 and PHP 7. I will upgrade them to latest Symonfy hopefully in May and by that time I will have to solve this issue.

I also didn't have a look on the Crawler class of Symfony 6 yet. Are you sure that there are no incompatible changes?

You are of course welcome to file a PR. If you manage to also change the Travis config in a way that all tests pass with Symonfy 6 and PHP 8 / 8.1 I'll be happy to merge your PR and tag a new release.

**Comment by wasinger** [comment]
Update: Today I realized that travis.org is no more and switched CI unit tests to Github Actions. So yeah, we have green tests again.
Then I wanted to allow Symfony 6 but tests fail because of modified method signatures in the base Crawler class.
So we need to change method signatures, too, and because that's a BC break we need a new major version...
I will probably do this within the next few weeks but PRs are welcome.

**Comment by wasinger** [comment]
Just released v3.0.0 for compatibility with Symfony 6.
