### ISSUE TITLE
Linebreaks inside of script tags are not handled correctly

### ISSUE THREAD

**Issue by m90** [wasinger/htmlpagedom#4]
I'm trying to manipulate the structure of a webpage that I crawl using `htmlpagedom`. When dumping the result into a string again, new lines will be gone, therefore causing problems with line comments `//` inside of script tags, i.e.:

```html
<script>
// this will be awesome
alert('Hello world');
</script>
```
will turn into:
```html
<script>// this will be awesomealert('Hello world');</script>
```

PHP looks like:
```php
$page = new HtmlPage(file_get_contents($url));

$page->filter('head')->append($stuff);
$page->filter('#some-id')->before($other_stuff);
$page->filter('body')->append($more_stuff);

return $page->save(); //this returns broken script content
```

is this behavior to be expected? Is this a bug? Can I work around this?

**Comment by wasinger** [comment]
I just added a test to the `HtmlPageTest` unit test class and it works for me, i.e. the line breaks are preserved (and on Travis the test also passes).

I guess it depends on the libxml version your PHP installation uses, since all we do when calling `$page->save()` is calling the `saveHTML()` function on the underlying DOM object.

Could you please check out the master branch, and see whether the phpunit tests pass on your machine? The test class for preserving the line breaks is `HtmlPageCrawlerTest::testScript()`. Feel free to modify it to reproduce the problem.
