### ISSUE TITLE
Non-latin UTF-8 characters

### ISSUE THREAD

**Issue by rafis** [wasinger/htmlpagedom#5]
After manipulating DOM and saving HTML, I'm getting all my not-latin utf-8 characters encoded with something like `htmlentities()`, for example:

    <span>&#1051;&#1086;&#1075;&#1080;&#1085</span>

They are correct, but consuming much more bytes.

**Comment by wasinger** [comment]
That's because when loading HTML documents or fragments, Crawler first converts all non-ASCII characters to entities (using `mb_convert_encoding($content, 'HTML-ENTITIES', 'UTF-8')`) to prevent problems with non-ascii characters.

You can convert those entities back to UTF-8 characters using  `mb_convert_encoding($content,  'UTF-8', 'HTML-ENTITIES')`.

**Comment by rafis** [comment]
Thank you!
